title: Learning Rate
email:
description: >- # this means to ignore newlines until "baseurl:"
  Artificial Intelligence, Machine Learning, Data Science concepts
  distilled to enhance mental clarity. 
baseurl: "/distill"
url: "https://tejomayk.github.io"

# Build settings
theme: jekyll-theme-dinky
plugins:
  - jekyll-feed
  - jekyll-sitemap


header_pages:
  - path: index.markdown
    title: Home
    order: 1
  - path: about.md
    title: About
    order: 2
  - path: general.md
    title: General
    order: 3
  - path: linear_algebra.md
    title: Linear Algebra
    order: 4
  - path: ml_systems.md
    title: ML Systems
    order: 5

author:
  name: "Tejomay Kapadia"


defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "default"
      author: "Tejomay Kapadia"

# GitHub Pages deployment
github:
  is_project_page: True
