title: Learning Rate
email:
description: >- # this means to ignore newlines until "baseurl:"
  Artificial Intelligence, Machine Learning, Data Science concepts
  distilled to enhance mental clarity. 
baseurl: "/distill"
url: "https://tejomayk.github.io"

# Build settings
theme: jekyll-theme-dinky
plugins:
  - jekyll-feed
  - jekyll-sitemap


header_pages:
  - index.markdown
  - about.md
  - linear_algebra.md

author:
  name: "Tejomay Kapadia"


defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "single"
      author: "Tejomay Kapadia"

# GitHub Pages deployment
github:
  is_project_page: True
